language : "pt"
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  #   priority: 5
  #   epochs: 20
  #   batch_size: 10
  #   featurizer:
  #     - name: FullDialogueTrackerFeaturizer
  #       state_featurizer:
  #         - name: LabelTokenizerSingleStateFeaturizer
  # - name: FallbackPolicy
  #   nlu_threshold: 0.6
  #   core_threshold: 0.6
  #   priority: 1
  - name: MappingPolicy

  # - name: KerasPolicy
  #   priority: 5
  #   epochs: 20
  #   batch_size: 10
  #   featurizer:
  #     - name: FullDialogueTrackerFeaturizer
  #       state_featurizer:
  #         - name: LabelTokenizerSingleStateFeaturizer
  - name: FallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    priority: 1
    fallback_action_name: "action_default_fallback"
  # - name: MemoizationPolicy
  #   priority: 2
  #   max_history: 2

  # - name: MemoizationPolicy
  # - name: KerasPolicy
  # - name: MappingPolicy
